# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

In [11]:
import numpy as np

## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

In [10]:
s = 0
grades = [77, 85, 56, 90, 66]
for i in grades:
    s += i
    
average = s/len(grades)
print("average of grades is {0:6.2f}. sum of grade is {1:0}".format(average, s))

average of grades is  74.80. sum of grade is 374


### 【示範】陣列導向

In [12]:
a = np.array(grades)
a.mean()

74.8

最大值

In [13]:
a.max()

90

標準差

In [14]:
a.std()

12.416118556135006

### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

In [18]:
prices = [1096.95, 596.95, 896.95]
NTD = []
for i in prices:
    NTD.append(i*31.71)
    
print(NTD)

[34784.2845, 18929.2845, 28442.2845]


先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [21]:
array_prices = np.array(prices)
array_NTD = array_prices*31.71
print(array_NTD)
type(array_NTD)

[34784.2845 18929.2845 28442.2845]


numpy.ndarray

哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [23]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])

w_grades = grades * weights


77.5


這還不是我們要的最終成績啊!

In [25]:
total_grade = w_grades.sum()
print(total_grade)

77.5


### 【提示】 array 還有很多函數可以用

可以先打入

    weighted_grades.
    
先不要按 `enter` 或 `shift-enter`, 而是按 `tab`...


### 【技巧】 一行完成成績計算

In [21]:
np.dot(grades, weights)

77.5

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [39]:
A = np.random.rand(50)
A

array([0.15056285, 0.25311876, 0.66589097, 0.04052545, 0.86436878,
       0.10267798, 0.76226565, 0.56649489, 0.30778919, 0.30677597,
       0.79027554, 0.44030581, 0.21394582, 0.55868182, 0.56039015,
       0.69633938, 0.89174293, 0.67826186, 0.9822508 , 0.59301571,
       0.35884163, 0.93295079, 0.40406172, 0.91357754, 0.84012644,
       0.31635213, 0.665313  , 0.75409637, 0.76644721, 0.81938813,
       0.41076865, 0.58259299, 0.24740925, 0.52055863, 0.22681269,
       0.52759553, 0.18980927, 0.802995  , 0.95955607, 0.61787734,
       0.271467  , 0.29130195, 0.59296352, 0.8919855 , 0.31263709,
       0.40515189, 0.36312634, 0.17912835, 0.35925728, 0.75039014])

In [40]:
A[0]

0.15056285078440468

### 【技巧】 檢查 A 的 `shape`

In [41]:
A.shape

(50,)

### 【技巧】 更改 A 的 shape

In [44]:
B = A.copy()
#B.shape=(5,10)
B.shape = (5,10)
B

array([[0.15056285, 0.25311876, 0.66589097, 0.04052545, 0.86436878,
        0.10267798, 0.76226565, 0.56649489, 0.30778919, 0.30677597],
       [0.79027554, 0.44030581, 0.21394582, 0.55868182, 0.56039015,
        0.69633938, 0.89174293, 0.67826186, 0.9822508 , 0.59301571],
       [0.35884163, 0.93295079, 0.40406172, 0.91357754, 0.84012644,
        0.31635213, 0.665313  , 0.75409637, 0.76644721, 0.81938813],
       [0.41076865, 0.58259299, 0.24740925, 0.52055863, 0.22681269,
        0.52759553, 0.18980927, 0.802995  , 0.95955607, 0.61787734],
       [0.271467  , 0.29130195, 0.59296352, 0.8919855 , 0.31263709,
        0.40515189, 0.36312634, 0.17912835, 0.35925728, 0.75039014]])

### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [51]:
B[0]
B[0,0]
B.reshape(10,-1)
B

B.shape = (10,-1)
B

array([[0.15056285, 0.25311876, 0.66589097, 0.04052545, 0.86436878],
       [0.10267798, 0.76226565, 0.56649489, 0.30778919, 0.30677597],
       [0.79027554, 0.44030581, 0.21394582, 0.55868182, 0.56039015],
       [0.69633938, 0.89174293, 0.67826186, 0.9822508 , 0.59301571],
       [0.35884163, 0.93295079, 0.40406172, 0.91357754, 0.84012644],
       [0.31635213, 0.665313  , 0.75409637, 0.76644721, 0.81938813],
       [0.41076865, 0.58259299, 0.24740925, 0.52055863, 0.22681269],
       [0.52759553, 0.18980927, 0.802995  , 0.95955607, 0.61787734],
       [0.271467  , 0.29130195, 0.59296352, 0.8919855 , 0.31263709],
       [0.40515189, 0.36312634, 0.17912835, 0.35925728, 0.75039014]])

### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

In [53]:
C = A.copy()
C.ravel()

array([0.15056285, 0.25311876, 0.66589097, 0.04052545, 0.86436878,
       0.10267798, 0.76226565, 0.56649489, 0.30778919, 0.30677597,
       0.79027554, 0.44030581, 0.21394582, 0.55868182, 0.56039015,
       0.69633938, 0.89174293, 0.67826186, 0.9822508 , 0.59301571,
       0.35884163, 0.93295079, 0.40406172, 0.91357754, 0.84012644,
       0.31635213, 0.665313  , 0.75409637, 0.76644721, 0.81938813,
       0.41076865, 0.58259299, 0.24740925, 0.52055863, 0.22681269,
       0.52759553, 0.18980927, 0.802995  , 0.95955607, 0.61787734,
       0.271467  , 0.29130195, 0.59296352, 0.8919855 , 0.31263709,
       0.40515189, 0.36312634, 0.17912835, 0.35925728, 0.75039014])

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [60]:
A = np.zeros(50)
A.shape = (5,-1)
A

A1 = np.zeros((3,4))
A1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 【技巧】 都是 1 的 array

In [63]:
B = np.ones(10)
B.shape = (2,5)
B

B1 = np.ones((2,5))
B1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 【技巧】單位矩陣

In [65]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 【技巧】給定範圍均勻生出 n 個點

In [67]:
np.linspace(0,100,100)

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

### 【技巧】`range` 的 array 版

就是 `arange`。

In [69]:
np.arange(1,10,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列後行」就可以!

我們先弄個 array 來練習。

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 【重點】 一列一列算下來是 `axis=0`

![axis=0](images/axis0.png)

In [77]:
A = np.arange(10).reshape(2,5)
print(A)
A.sum(axis = 0)

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([ 5,  7,  9, 11, 13])

### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

In [78]:
A.sum(axis = 1)

array([10, 35])

### 【提示】當然也有可能全部算

In [54]:
A.sum()

45

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [82]:
L = np.array([3, -2, -1, 5, 7, -3])

我們可以很白痴的自己判斷...<br>
c = np.array([True,False,False,True,True,False])

In [83]:
c = np.array([True,False,False,True,True,False])

這是做啥呢? 我們可以瞬間...

In [84]:
L[c]

array([3, 5, 7])

除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!

In [85]:
L > 0

array([ True, False, False,  True,  True, False])

這有點強, 我們還可以一次到位!

In [86]:
L[L>0]

array([3, 5, 7])

## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

In [88]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
B = A[3:7]
B

array([3, 4, 5, 6])

### 【技巧】2維陣列切法

記得先列後行!

In [96]:

A.shape = (2,5)


要所有的row, 切出行 1-3 位置。

In [97]:
A[:,1:3]

array([[1, 2],
       [6, 7]])

要所有的行col, 切出第 1 列row!

In [98]:
A[1,:]

array([5, 6, 7, 8, 9])

## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [100]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [105]:
X = np.c_[x,y]
X.shape
X

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [106]:
Y = np.r_[x,y]
Y.shape
Y

array([1, 2, 3, 4, 5, 6, 7, 8])

### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)

In [107]:
X[:,0]

array([1, 2, 3, 4])

In [108]:
X[:,1]

array([5, 6, 7, 8])